### ISSUE TITLE
Ordering of panels when grouping

### ISSUE THREAD

**Issue by manuelreif** [jbryer/likert#100] opened 2019-03-16 14:12 UTC
Hi!  
Thank you for this awesome package!
I have a problem when creating a likert plot with grouping. I would like to keep the item order as in the submitted data.frame ... but the panels in the plot are sorted alphabetically.

```r 
require(likert)
data(pisaitems)

##### Item 24: Reading Attitudes
items24 <- pisaitems[,substr(names(pisaitems), 1,5) == 'ST24Q']
head(items24); ncol(items24)

names(items24) <- c(
			ST24Q01="I read only if I have to.",
			ST24Q02="Reading is one of my favorite hobbies.",
			ST24Q03="I like talking about books with other people.",
			ST24Q04="I find it hard to finish books.",
			ST24Q05="I feel happy if I receive a book as a present.",
			ST24Q06="For me, reading is a waste of time.",
			ST24Q07="I enjoy going to a bookstore or a library.",
			ST24Q08="I read only to get information that I need.",
			ST24Q09="I cannot sit still and read for more than a few minutes.",
			ST24Q10="I like to express my opinions about books I have read.",
			ST24Q11="I like to exchange books with my friends.")

l24g <- likert(items24, grouping=pisaitems$CNT)
plot(l24g)
```

I would like to keep the item: **I read only if I have to.** as the first Item displayed in the first panel.
I searched the functions and arguments, but couldn't find out how to chance the ordering.

Thank you!
Manuel

**Comment by jbryer** [comment] 2019-03-26 00:06
When I run the code below, the panels are in the order they appear in the data.frame. The second option reverses the columns and they are presented in reverse order. Can you make sure you have the latest version of ggplot2 and are running the version from Github? I hope to release a new version to CRAN at the end of April.

```
library(likert)
data(pisaitems)
items24 <- pisaitems[,substr(names(pisaitems), 1,5) == 'ST24Q']
head(items24); ncol(items24)

names(items24) <- c(
	ST24Q01="I read only if I have to.",
	ST24Q02="Reading is one of my favorite hobbies.",
	ST24Q03="I like talking about books with other people.",
	ST24Q04="I find it hard to finish books.",
	ST24Q05="I feel happy if I receive a book as a present.",
	ST24Q06="For me, reading is a waste of time.",
	ST24Q07="I enjoy going to a bookstore or a library.",
	ST24Q08="I read only to get information that I need.",
	ST24Q09="I cannot sit still and read for more than a few minutes.",
	ST24Q10="I like to express my opinions about books I have read.",
	ST24Q11="I like to exchange books with my friends.")

l24g <- likert(items24, grouping=pisaitems$CNT)
plot(l24g)

l24g.reversed <- likert(items24[,ncol(items24):1], grouping = pisaitems$CNT)
plot(l24g.reversed)
```

**Comment by jbryer** [comment] 2019-04-03 13:25
I am closing since I can't reproduce the issue.

**Closed by jbryer** 2019-04-03 13:25 UTC
